env:
  TERM: xterm-256color
window:
  opacity: 1.0
  padding:
    x: 0
    y: 0
  decorations: transparent
  startup_mode: SimpleFullscreen
# shell:
#   program: /opt/homebrew/bin/fish
scrolling:
  history: 0
cursor:
  style: Block
  unfocused_hollow: true
font:
  normal:
    family: MonoLisa Custom
    style: Regular
  bold:
    family: MonoLisa Custom
    style: Bold
  italic:
    family: MonoLisa Custom
    style: Italic
  bold_italic:
    family: MonoLisa Custom
    style: Bold Italic
  size: 18
draw_bold_text_with_bright_colors: false
# github Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x1f1f28'
    foreground: '0xdcd7ba'

  # Normal colors
  normal:
    black: '0x090618'
    red: '0xc34043'
    green: '0x76946a'
    yellow: '0xc0a36e'
    blue: '0x7e9cd8'
    magenta: '0x957fb8'
    cyan: '0x6a9589'
    white: '0xc8c093'

  # Bright colors
  bright:
    black: '0x727169'
    red: '0xe82424'
    green: '0x98bb6c'
    yellow: '0xe6c384'
    blue: '0x7fb4ca'
    magenta: '0x938aa9'
    cyan: '0x7aa89f'
    white: '0xdcd7ba'
  selection:
    background: '0x2d4f67'
    foreground: '0xc8c093'

  indexed_colors:
    - { index: 16, color: '0xffa066' }
    - { index: 17, color: '0xff5d62' }
shell:
  program: /bin/zsh
  args:
    - --login
selection:
  save_to_clipboard: false
mouse:
  hints:
    launcher:
      program: open
      args:
        - -a
        - Safari
theme: Kanagawa
