live_config_reload: true
env:
  TERM: xterm-256color
shell:
  program: /opt/homebrew/bin/fish
  args:
    - --login
window:
  opacity: 1.0
  padding:
    x: 0
    y: 0
  decorations: transparent
  startup_mode: SimpleFullscreen
cursor:
  unfocused_hollow: true
  vi_mode_style:
    shape: Block
font:
  normal:
    family: MonoLisaLight Nerd Font
    style: Light
  bold:
    family: MonoLisa Nerd Font
    style: Bold
  italic:
    family: MonoLisa Nerd Font
    style: Regular Italic
  bold_italic:
    family: MonoLisa Nerd Font
    style: Bold Italic
  size: 14
  offset:
    x: 0
    y: 0
# github Alacritty Colors
# Catpuccin - Frappe
colors:
  # Default colors
  primary:
    background: '#24273A' # base
    foreground: '#CAD3F5' # text
    # Bright and dim foreground colors
    dim_foreground: '#CAD3F5' # text
    bright_foreground: '#CAD3F5' # text

  # Cursor colors
  cursor:
    text: '#24273A' # base
    cursor: '#F4DBD6' # rosewater
  vi_mode_cursor:
    text: '#24273A' # base
    cursor: '#B7BDF8' # lavender

  # Search colors
  search:
    matches:
      foreground: '#24273A' # base
      background: '#A5ADCB' # subtext0
    focused_match:
      foreground: '#24273A' # base
      background: '#A6DA95' # green
  footer_bar:
    foreground: '#24273A' # base
    background: '#A5ADCB' # subtext0

  # Keyboard regex hints
  hints:
    start:
      foreground: '#24273A' # base
      background: '#EED49F' # yellow
    end:
      foreground: '#24273A' # base
      background: '#A5ADCB' # subtext0

  # Selection colors
  selection:
    text: '#24273A' # base
    background: '#F4DBD6' # rosewater

  # Normal colors
  normal:
    black: '#494D64' # surface1
    red: '#ED8796' # red
    green: '#A6DA95' # green
    yellow: '#EED49F' # yellow
    blue: '#8AADF4' # blue
    magenta: '#F5BDE6' # pink
    cyan: '#8BD5CA' # teal
    white: '#B8C0E0' # subtext1

  # Bright colors
  bright:
    black: '#5B6078' # surface2
    red: '#ED8796' # red
    green: '#A6DA95' # green
    yellow: '#EED49F' # yellow
    blue: '#8AADF4' # blue
    magenta: '#F5BDE6' # pink
    cyan: '#8BD5CA' # teal
    white: '#A5ADCB' # subtext0

  # Dim colors
  dim:
    black: '#494D64' # surface1
    red: '#ED8796' # red
    green: '#A6DA95' # green
    yellow: '#EED49F' # yellow
    blue: '#8AADF4' # blue
    magenta: '#F5BDE6' # pink
    cyan: '#8BD5CA' # teal
    white: '#B8C0E0' # subtext1

  indexed_colors:
    - { index: 16, color: '#F5A97F' }
    - { index: 17, color: '#F4DBD6' }
selection:
  save_to_clipboard: false
mouse:
  hints:
    launcher:
      program: open
      args:
        - -a
        - Safari
theme: Catppuccin-Macchiato
