env:
  TERM: xterm-256color
window:
  padding:
    x: 0
    y: 0
  decorations: transparent
  startup_mode: SimpleFullscreen
scrolling:
  history: 0
font:
  normal:
    family: JetBrains Mono        
    style: Regular
  bold:
    family: JetBrains Mono
    style: Bold
  italic:
    family: JetBrains Mono
    style: Italic
  size: 12
  use_thin_strokes: true
draw_bold_text_with_bright_colors: false
colors:
  primary:
    background: "#282a36"
    foreground: "#f8f8f2"
  normal:
    black: "#000000"
    red: "#ff5555"
    green: "#50fa7b"
    yellow: "#f1fa8c"
    blue: "#caa9fa"
    magenta: "#ff79c6"
    cyan: "#8be9fd"
    white: "#bfbfbf"
  bright:
    black: "#575b70"
    red: "#ff6e67"
    green: "#5af78e"
    yellow: "#f4f99d"
    blue: "#caa9fa"
    magenta: "#ff92d0"
    cyan: "#9aedfe"
    white: "#e6e6e6"
background_opacity: 1
shell:
  program: /bin/zsh
  args:
    - --login
mouse:
  hints:
    launcher:
      program: open
      args:
        - -a
        - Safari
