env:
  TERM: xterm-256color
window:
  padding:
    x: 0
    y: 0
  decorations: transparent
  startup_mode: SimpleFullscreen
scrolling:
  history: 0
font:
  normal:
    family: JetBrains Mono
    style: Light
  bold:
    family: JetBrains Mono
    style: Bold
  italic:
    family: JetBrains Mono
    style: Italic
  size: 12
  use_thin_strokes: true
draw_bold_text_with_bright_colors: false
colors:
  primary:
    background: "#2D2A2E"
    foreground: "#FCFCFA"
  normal:
    black: "#403E41"
    red: "#FF6188"
    green: "#A9DC76"
    yellow: "#FFD866"
    blue: "#FC9867"
    magenta: "#AB9DF2"
    cyan: "#78DCE8"
    white: "#FCFCFA"
  bright:
    black: "#727072"
    red: "#FF6188"
    green: "#A9DC76"
    yellow: "#FFD866"
    blue: "#FC9867"
    magenta: "#AB9DF2"
    cyan: "#78DCE8"
    white: "#FCFCFA"
background_opacity: 1
shell:
  program: /bin/zsh
  args:
    - --login
mouse:
  hints:
    launcher:
      program: open
      args:
        - -a
        - Safari
