[cursor]
unfocused_hollow = true

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "Berkeley Mono Variable"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono Variable"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono Variable"
style = "Regular Italic"

[font.normal]
family = "Berkeley Mono Variable"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = false

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "transparent"
opacity = 1.0
startup_mode = "SimpleFullscreen"

[window.padding]
x = 0
y = 0
